SELECT
    id,
    month,
    os_number,
    nf_type,
    ride_date,
    EXTRACT(YEAR FROM ride_date)::INTEGER AS ride_year,
    EXTRACT(MONTH FROM ride_date)::INTEGER AS ride_month,
    EXTRACT(DOW FROM ride_date)::INTEGER AS ride_dow,   -- 0=Sun, 6=Sat
    company,
    requester,
    channel,
    vehicle_plate,
    driver,
    km_empty,
    km_loaded,
    km_total,
    EXTRACT(EPOCH FROM company_time) / 60 AS company_time_minutes,
    EXTRACT(EPOCH FROM driver_time) / 60 AS driver_time_minutes,
    origin,
    destination,
    passenger_count,
    service_type,
    trip_type,
    toll,
    parking,
    idle_time_billing,
    transit_fare,
    return_billing,
    ride_price,
    surcharges,
    total,
    night_km,
    holiday_km,
    sunday_km,
    price_per_km,
    cost_per_passenger,
    status
FROM rides
ORDER BY ride_date, os_number
